<?php
SESSION_START();
SESSION_DESTROY();
{
    setcookie('admin_id',false,time()-7*24*60*60);
    setcookie('admin_username',false,time()-7*24*60*60);
    setcookie('admin_email',false,time()-7*24*60*60);
}
header('location:index.php');
?>